### PR TITLE
Update lib structure

### PR DESCRIPTION
**Pull request by helderberto**
update package.json microbundle build folder ./src/*.js
update lib to ./src/histore.js
update .gitignore prevent more files

### CODE REVIEW

**Comment by developit** [comment]
I'm fine moving the library into `src`, but I don't agree with the gitignore.

**Comment by helderberto** [comment]
Could u check again? :)

**Comment by KnupMan** [comment]
@helderburato there is missing the empty end line, but previously it was there
image

**Comment by helderberto** [comment]
Fixed. Thanks @KnupMan!

Could u review again @developit ? :)

**Comment by developit** [comment]
Still need to delete the package-lock.json:

```
git rm --cached package-lock.json
```

**Comment by helderberto** [comment]
Done. @developit

**Review by developit — APPROVED** [review]

**Comment by developit** [comment]
Great, thanks!

**Pull request closed without merging**
